-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admins
(
    admin_id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(200) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_order_accept boolean DEFAULT true,
    CONSTRAINT admins_pkey PRIMARY KEY (admin_id),
    CONSTRAINT admins_email_key UNIQUE (email),
    CONSTRAINT admins_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.customers
(
    customer_id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    phone character varying(15) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    dob date,
    CONSTRAINT customers_pkey PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS public.menu_category
(
    category_id serial NOT NULL,
    category_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT menu_category_pkey PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public.menu_items
(
    item_id serial NOT NULL,
    item_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    category_id integer,
    price numeric(10, 2) NOT NULL,
    image_url text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    is_available boolean DEFAULT true,
    CONSTRAINT menu_items_pkey PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public.order_items
(
    order_item_id serial NOT NULL,
    order_id integer,
    item_id integer,
    quantity integer NOT NULL,
    price numeric(10, 2) NOT NULL,
    CONSTRAINT order_items_pkey PRIMARY KEY (order_item_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    order_id serial NOT NULL,
    customer_id integer,
    table_number character varying(20) COLLATE pg_catalog."default" NOT NULL,
    total_amount numeric(10, 2) DEFAULT 0,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    payment_id serial NOT NULL,
    order_id integer,
    amount numeric(10, 2),
    payment_status character varying(20) COLLATE pg_catalog."default",
    payment_method character varying(50) COLLATE pg_catalog."default",
    razorpay_payment_id character varying(200) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payments_pkey PRIMARY KEY (payment_id)
);

CREATE TABLE IF NOT EXISTS public.ratings
(
    rating_id serial NOT NULL,
    customer_id integer NOT NULL,
    rating_value integer NOT NULL,
    review_text text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    item_id integer,
    order_id integer,
    CONSTRAINT ratings_pkey PRIMARY KEY (rating_id),
    CONSTRAINT unique_customer_item_rating UNIQUE (customer_id, item_id),
    CONSTRAINT unique_customer_order_rating UNIQUE (customer_id, order_id)
);

COMMENT ON TABLE public.ratings
    IS 'Customer ratings and reviews - normalized design with customer_id reference only';

COMMENT ON COLUMN public.ratings.rating_id
    IS 'Primary key - unique rating identifier';

COMMENT ON COLUMN public.ratings.customer_id
    IS 'Foreign key to customers table - one rating per customer';

COMMENT ON COLUMN public.ratings.rating_value
    IS 'Rating value from 1 to 5 stars';

COMMENT ON COLUMN public.ratings.review_text
    IS 'Optional text review from customer';

COMMENT ON COLUMN public.ratings.created_at
    IS 'Timestamp when rating was created';

CREATE TABLE IF NOT EXISTS public.sessions
(
    session_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    customer_id integer,
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamp without time zone NOT NULL,
    last_activity timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    id serial NOT NULL,
    admin_id integer,
    CONSTRAINT sessions_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.menu_items
    ADD CONSTRAINT menu_items_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.menu_category (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_menu_items_category
    ON public.menu_items(category_id);


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_item_id_fkey FOREIGN KEY (item_id)
    REFERENCES public.menu_items (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_order_items_item_id
    ON public.order_items(item_id);


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_order_items_order_id
    ON public.order_items(order_id);


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_orders_customer_id
    ON public.orders(customer_id);


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_payments_order_id
    ON public.payments(order_id);


ALTER TABLE IF EXISTS public.ratings
    ADD CONSTRAINT fk_ratings_customer FOREIGN KEY (customer_id)
    REFERENCES public.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_ratings_customer_id
    ON public.ratings(customer_id);


ALTER TABLE IF EXISTS public.ratings
    ADD CONSTRAINT fk_ratings_item FOREIGN KEY (item_id)
    REFERENCES public.menu_items (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_ratings_item_id
    ON public.ratings(item_id);


ALTER TABLE IF EXISTS public.ratings
    ADD CONSTRAINT fk_ratings_order FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_ratings_order_id
    ON public.ratings(order_id);


ALTER TABLE IF EXISTS public.sessions
    ADD CONSTRAINT fk_sessions_admin FOREIGN KEY (admin_id)
    REFERENCES public.admins (admin_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sessions_admin_id
    ON public.sessions(admin_id);


ALTER TABLE IF EXISTS public.sessions
    ADD CONSTRAINT sessions_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sessions_customer_id
    ON public.sessions(customer_id);

-- Data Seeding
INSERT INTO public.admins (username, password, name, email) 
VALUES ('ravi', '8ff9538e65e6781d654b811f88161d12455935ffb8f470815063b6ab6cb7fdff', 'Ravi Admin', 'ravi@HotByte.in')
ON CONFLICT (username) DO UPDATE SET password = EXCLUDED.password;

INSERT INTO public.menu_category (category_id, category_name) VALUES
(1, 'Starters'),
(2, 'Main Course'),
(3, 'Desserts'),
(4, 'Beverages')
ON CONFLICT (category_id) DO NOTHING;

INSERT INTO public.menu_items (item_name, category_id, price, image_url, description, is_available) VALUES
('Paneer Tikka Angara', 1, 1.00, 'https://images.pexels.com/photos/3928854/pexels-photo-3928854.jpeg', 'Spicy grilled cottage cheese with bell peppers.', true),
('Crispy Corn', 1, 1.00, 'https://images.pexels.com/photos/12916892/pexels-photo-12916892.jpeg', 'Golden fried sweet corn kernels with spices.', true),
('Hara Bhara Kabab', 1, 1.00, 'https://images.pexels.com/photos/12392842/pexels-photo-12392842.jpeg', 'Healthy spinach and green pea patties.', true),
('Veg Manchurian', 1, 1.00, 'https://images.pexels.com/photos/13524671/pexels-photo-13524671.jpeg', 'Indo-Chinese style vegetable balls in spicy gravy.', true),
('Spring Rolls', 1, 1.00, 'https://images.pexels.com/photos/11267448/pexels-photo-11267448.jpeg', 'Crispy rolls stuffed with sautÃ©ed vegetables.', true),
('Chilli Paneer', 1, 1.00, 'https://images.pexels.com/photos/13010724/pexels-photo-13010724.jpeg', 'Cottage cheese cubes tossed in spicy chilli sauce.', true),
('Butter Chicken', 2, 249.00, 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg', 'Classic creamy chicken curry in tomato gravy.', true),
('Hyderabadi Biryani', 2, 1.00, 'https://images.pexels.com/photos/12737651/pexels-photo-12737651.jpeg', 'Authentic slow-cooked basmati rice with spices.', true),
('Veg Diwani Handi', 2, 1.00, 'https://images.pexels.com/photos/9609842/pexels-photo-9609842.jpeg', 'Assorted vegetables cooked in a rich handi gravy.', true),
('Fish Curry', 2, 1.00, 'https://images.pexels.com/photos/14731635/pexels-photo-14731635.jpeg', 'Traditional coastal style fish curry.', true),
('Paneer Butter Masala', 2, 1.00, 'https://images.pexels.com/photos/9609848/pexels-photo-9609848.jpeg', 'Cottage cheese in a rich and creamy tomato sauce.', true),
('Dal Tadka', 2, 1.00, 'https://images.pexels.com/photos/12392837/pexels-photo-12392837.jpeg', 'Yellow lentils tempered with aromatic spices.', true),
('Laccha Paratha', 2, 1.00, 'https://images.pexels.com/photos/11115802/pexels-photo-11115802.jpeg', 'Multi-layered flaky whole wheat flatbread.', true),
('Butter Naan', 2, 1.00, 'https://images.pexels.com/photos/9510204/pexels-photo-9510204.jpeg', 'Soft and buttery leavened flatbread.', true),
('Jeera Rice', 2, 1.00, 'https://images.pexels.com/photos/12737650/pexels-photo-12737650.jpeg', 'Basmati rice tempered with cumin seeds.', true),
('Kesari Firni', 3, 1.00, 'https://images.pexels.com/photos/10103759/pexels-photo-10103759.jpeg', 'Traditional saffron infused ground rice pudding.', true),
('Gulab Jamun', 3, 1.00, 'https://images.pexels.com/photos/10103762/pexels-photo-10103762.jpeg', 'Soft khoya balls soaked in sugar syrup.', true),
('Ras Malai', 3, 1.00, 'https://images.pexels.com/photos/10103760/pexels-photo-10103760.jpeg', 'Flattened cottage cheese balls in thickened milk.', true),
('Masala Chaas', 4, 1.00, 'https://images.pexels.com/photos/15801053/pexels-photo-15801053.jpeg', 'Refreshing spiced buttermilk with mint.', true),
('Mango Lassi', 4, 1.00, 'https://images.pexels.com/photos/11545648/pexels-photo-11545648.jpeg', 'Thick yogurt drink blended with sweet mangoes.', true),
('Fresh Lime Soda', 4, 1.00, 'https://images.pexels.com/photos/4021983/pexels-photo-4021983.jpeg', 'Zesty lime soda served sweet or salted.', true),
('Mineral Water', 4, 1.00, 'https://images.pexels.com/photos/416528/pexels-photo-416528.jpeg', 'Packaged 1L drinking water.', true);

END;

